# ~/.config/alacritty/alacritty.toml
[general]
import = ["~/.config/alacritty/tokyo_night.toml"]

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 10

#[font.features]
# Aktifkan ligatur untuk Fira Code
#ss01 = 1  # Stylistic Set 1
#ss02 = 1  # Stylistic Set 2
#ss03 = 1  # Stylistic Set 3
#ss04 = 1  # Stylistic Set 4
#ss05 = 1  # Stylistic Set 5

[window]
opacity = 0.8
padding = { x = 10, y = 10 }
dimensions = { columns = 120, lines = 28 }
#position = { x = 1, y = 1}
#decorations = "Full"  # none|transparent|full

[scrolling]
history = 10000
multiplier = 3

[colors]
primary = { background = "#282c34", foreground = "#abb2bf" }

#[cursor]
#style = "Block"
#blinking = "On"

[selection]
save_to_clipboard = true

#[shell]
#program = "/bin/bash"
#args = ["--login"]

[env]
TERM = "xterm-256color"
